### PR TITLE
Fix Multi-Select

### LINKED ISSUE #179: Selection state is not cleared if a selected entry is deleted by way of trash can (in the listing) rather than the uninstall `remove` UI
See here for after state
Image

### PR DESCRIPTION
**Pull request by kaicardenas0618**
Fixes #179.

### CODE REVIEW

File: frontend/src/main.tsx [hunk 1]
```diff
@@ -41,9 +41,21 @@ const preventGestureZoom = (e: Event) => {
   e.stopPropagation();
 };
 
-document.addEventListener('gesturestart', preventGestureZoom as EventListener, true);
-document.addEventListener('gesturechange', preventGestureZoom as EventListener, true);
-document.addEventListener('gestureend', preventGestureZoom as EventListener, true);
+document.addEventListener(
```
Comment (ahkimn) [inline frontend/src/main.tsx]: This gonna merge conflict with #189 :/
